# Generated by Django 5.0.1 on 2024-01-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Название категории спорта')),
                ('description', models.TextField(verbose_name='Описание категории спорта')),
            ],
            options={
                'verbose_name': 'Категория спорта',
                'verbose_name_plural': 'Категории спорта',
            },
        ),
    ]
