# Generated by Django 5.0.1 on 2024-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные заметки о здоровье'),
        ),
        migrations.AddField(
            model_name='health',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ИМТ'),
        ),
        migrations.AddField(
            model_name='health',
            name='bmi_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Категория ИМТ'),
        ),
    ]
