# Generated by Django 5.0.1 on 2024-02-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        ('users', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='health',
            options={'verbose_name': 'Запись о здоровье', 'verbose_name_plural': 'Записи о здоровье'},
        ),
        migrations.RemoveField(
            model_name='health',
            name='user_id',
        ),
        migrations.AddField(
            model_name='health',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='health',
            name='additional_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные заметки'),
        ),
        migrations.AlterField(
            model_name='health',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Индекс массы тела (ИМТ)'),
        ),
        migrations.AlterField(
            model_name='health',
            name='bmi_category',
            field=models.CharField(blank=True, choices=[('underweight', 'Ниже нормального веса'), ('normal', 'Нормальный вес'), ('overweight', 'Избыточный вес'), ('obese_1', 'Ожирение I степени'), ('obese_2', 'Ожирение II степени')], max_length=50, null=True, verbose_name='Категория ИМТ'),
        ),
        migrations.AlterField(
            model_name='health',
            name='health_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор записи о здоровье'),
        ),
        migrations.AlterField(
            model_name='health',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Частота сердечных сокращений (уд./мин.)'),
        ),
        migrations.AlterField(
            model_name='health',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='health',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес (кг)'),
        ),
    ]
