# Generated by Django 5.0.1 on 2024-01-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255, verbose_name='Название спортобъекта')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение спортобъекта')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость спортобъекта')),
                ('equipment_available', models.BooleanField(verbose_name='Наличие оборудования на спортобъекте')),
                ('trainer_available', models.BooleanField(verbose_name='Наличие тренера на спортобъекте')),
            ],
            options={
                'verbose_name': 'Спортобъект',
                'verbose_name_plural': 'Спортобъекты',
            },
        ),
    ]
