# Generated by Django 5.0.1 on 2024-01-19 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField(verbose_name='Дата тренировки')),
                ('exercise_type', models.CharField(max_length=50, verbose_name='Тип упражнения')),
                ('duration', models.DurationField(verbose_name='Продолжительность тренировки')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Дополнительные заметки о тренировке')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
    ]
