# Generated by Django 5.0.1 on 2024-02-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_user_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_date', models.DateField()),
                ('exercise_type', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
