# Generated by Django 5.0.1 on 2024-02-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_of_birth'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user_id',
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(verbose_name='Продолжительность тренировки'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise_type',
            field=models.CharField(max_length=100, verbose_name='Тип упражнения'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_date',
            field=models.DateField(verbose_name='Дата тренировки'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор тренировки'),
        ),
    ]
