# Generated by Django 5.0.1 on 2024-01-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports_facilities', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание мероприятия')),
                ('organizer', models.CharField(max_length=100, verbose_name='Организатор мероприятия')),
                ('facilities', models.ManyToManyField(blank=True, related_name='events', to='sports_facilities.sportsfacility', verbose_name='Спортобъекты')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
