# Generated by Django 5.0.2 on 2024-03-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_link', models.URLField(verbose_name='Ссылка на дополнительные данные')),
                ('additional_info', models.TextField(verbose_name='Дополнительная информация о мероприятии')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Подробности мероприятия',
                'verbose_name_plural': 'Подробности мероприятий',
            },
        ),
    ]
