# Generated by Django 5.0.2 on 2024-03-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdetails',
            name='additional_info',
        ),
    ]
