# Generated by Django 5.0.1 on 2024-02-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportFacilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsfacility',
            options={'verbose_name': 'Спортивный объект', 'verbose_name_plural': 'Спортивные объекты'},
        ),
        migrations.AlterField(
            model_name='sportsfacility',
            name='capacity',
            field=models.IntegerField(verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='sportsfacility',
            name='equipment_available',
            field=models.BooleanField(default=False, verbose_name='Наличие оборудования'),
        ),
        migrations.AlterField(
            model_name='sportsfacility',
            name='facility_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Уникальный идентификатор спортивного объекта'),
        ),
        migrations.AlterField(
            model_name='sportsfacility',
            name='facility_name',
            field=models.CharField(max_length=100, verbose_name='Название спортивного объекта'),
        ),
        migrations.AlterField(
            model_name='sportsfacility',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='sportsfacility',
            name='trainer_available',
            field=models.BooleanField(default=False, verbose_name='Наличие тренера'),
        ),
    ]
